[package]
name = "chtholly"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.8.4"
pest_derive = "2.8.4"

[lib]
name = "chtholly_lib"
path = "src/lib.rs"

[[bin]]
name = "chtholly"
path = "src/main.rs"
