[package]
name = "chtholly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.4.0", features = ["llvm14-0"] }
clap = { version = "4.4.18", features = ["derive"] }
