[package]
name = "chtholly_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.7.0", features = ["llvm17-0"] }
llvm-sys = { version = "170", features = ["prefer-dynamic"] }
